version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080" #Puerto 80 en producción
    env_file: ./.env
    environment:
      NODE_ENV: production
  

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local