version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Puerto para pruebas
    env_file: ./.env
    environment:
      NODE_ENV: development
  

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local